### PR TITLE
Wasix fixes

### PR DESCRIPTION
**Pull request by john-sharratt**

### CODE REVIEW

**Comment by joseluisq** [comment]
Any details about the PR?

**Comment by joseluisq** [comment]
Sorry for being too disconnected. After reading today [the announcement](https://wasmer.io/posts/announcing-wasix), adding support for `wasm32-wasi` should just be awesome!

If there is something that I can do feel free to let me know.

**Comment by joseluisq** [comment]
Just FYI, I included a small page about the Wasmer SWS package in [the project docs](https://static-web-server.net/features/webassembly/).

**Comment by palant** [comment]
This looks interesting. However, using an outdated tokio fork isn’t really a great option and a temporary solution at best. Personally, I’d rather track https://github.com/tokio-rs/tokio/issues/4827 – this proposal can be revisited once WASIX is mature enough that tokio can support it officially.

**Comment by banocean** [comment]
> This looks interesting. However, using an outdated tokio fork isn’t really a great option and a temporary solution at best. Personally, I’d rather track [tokio-rs/tokio#4827](https://github.com/tokio-rs/tokio/issues/4827) – this proposal can be revisited once WASIX is mature enough that tokio can support it officially.

I don't think tokio has considered supporting wasix, they plan supporting wasip2 as far as I know

**Comment by joseluisq** [comment]
> I don't think tokio has considered supporting wasix, they plan supporting wasip2 as far as I know

Exactly, I read it on the upstream issue recently.

--

On the other hand, what I can see is that Wasmer folks are keeping its fork up-to-date and dealing with the Wasix compatibility issues. So if users want to build SWS today for Wasix then they can via https://github.com/wasix-org/static-web-server/commits/master/.

@john-sharratt Maybe what we can do is to close this PR and advice users explicitly on our docs if they want to build SWS for Wasix or just refer them via a link to Wasmer site for details.

**Pull request closed without merging**
