### PR TITLE
Experimental Prometheus support for providing Tokio Runtime metrics

### LINKED ISSUE #125: Simple prometheus metrics
**Is your feature request related to a problem? Please describe.**
I'd like to observe some minimal metrics.

**Describe the solution you'd like**
Expose prometheus metrics 

**Describe alternatives you've considered**
Looking for a rust library to possibly plugin into.

**Additional context**
Add any other context or screenshots about the feature request here if needed.

### PR DESCRIPTION
**Pull request by joseluisq**
## Description

Implements an optional Prometheus metrics endpoint at `/metrics`. Currently provides [Tokio RuntimeMetrics](https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html) via [tokio-metrics-collector](https://github.com/Hanaasagi/tokio-metrics-collector), requiring `tokio_unstable`. I tried implementing task metrics for the HTTPS redirect Tokio tasks, but no metrics were produced.

```
      --experimental-metrics[=<EXPERIMENTAL_METRICS>]
          Add a /metrics endpoint that returns a Prometheus metrics response [env: SERVER_EXPERIMENTAL_METRICS=] [default: false] [possible values: true, false]
```

## Related Issue

Fixes #125

## Motivation and Context

Many cloud-native environments (eg Kubernetes) use the Prometheus metrics format for performance monitoring.

## How Has This Been Tested?

`cargo run`, `make test`, and CI on forked master branch. Build fails on Windows platforms, possibly due to missing RuntimeMetrics.

```sh
$ curl -i http://localhost/metrics
# HTTP/1.1 200 OK
# content-type: text/plain; charset=utf-8
# content-length: 2568
# date: Fri, 02 Feb 2024 00:07:21 GMT

# HELP tokio_budget_forced_yield_count Returns the number of times that tasks have been forced to yield back to the scheduler after exhausting their task budgets.
# TYPE tokio_budget_forced_yield_count counter
tokio_budget_forced_yield_count 0
# HELP tokio_elapsed Total amount of time elapsed since observing runtime metrics.
# TYPE tokio_elapsed counter
tokio_elapsed 135.077963667
# HELP tokio_injection_queue_depth The number of tasks currently scheduled in the runtime’s injection queue.
# TYPE tokio_injection_queue_depth gauge
tokio_injection_queue_depth 0
# HELP tokio_io_driver_ready_count Returns the number of ready events processed by the runtime’s I/O driver.
# TYPE tokio_io_driver_ready_count counter
tokio_io_driver_ready_count 70
# HELP tokio_num_remote_schedules The number of tasks scheduled from outside of the runtime.
# TYPE tokio_num_remote_schedules counter
tokio_num_remote_schedules 14
# HELP tokio_total_busy_duration The amount of time worker threads were busy.
# TYPE tokio_total_busy_duration counter
tokio_total_busy_duration 0.01203866
# HELP tokio_total_local_queue_depth The total number of tasks currently scheduled in workers’ local queues.
# TYPE tokio_total_local_queue_depth gauge
tokio_total_local_queue_depth 0
# HELP tokio_total_local_schedule_count The number of tasks scheduled from worker threads.
# TYPE tokio_total_local_schedule_count counter
tokio_total_local_schedule_count 13
# HELP tokio_total_noop_count The number of times worker threads unparked but performed no work before parking again.
# TYPE tokio_total_noop_count counter
tokio_total_noop_count 58
# HELP tokio_total_overflow_count The number of times worker threads saturated their local queues.
# TYPE tokio_total_overflow_count counter
tokio_total_overflow_count 0
# HELP tokio_total_park_count The number of times worker threads parked.
# TYPE tokio_total_park_count counter
tokio_total_park_count 83
# HELP tokio_total_polls_count The number of tasks that have been polled across all worker threads.
# TYPE tokio_total_polls_count counter
tokio_total_polls_count 25
# HELP tokio_total_seal_operations The number of times worker threads stole tasks from another worker thread.
# TYPE tokio_total_seal_operations counter
tokio_total_seal_operations 0
# HELP tokio_total_steal_count The number of tasks worker threads stole from another worker thread.
# TYPE tokio_total_steal_count counter
tokio_total_steal_count 0
# HELP tokio_workers_count The number of worker threads used by the runtime.
# TYPE tokio_workers_count gauge
tokio_workers_count 8
```

--

This PR was created by @pl4nty first on #296

### CODE REVIEW

**Comment by joseluisq** [comment]
@pl4nty JFYI I addressed the feedback of the previous PR and I made a few changes.

- The feature was renamed to `experimental-metrics`.
- The feature is enabled only for Unix/Linux.
- There is a generic test case, which I think is enough for now.

**Comment by joseluisq** [comment]
> I can build on FreeBSD by passing RUSTFLAGS="--cfg tokio_unstable" to cargo build --release.
> 
> I'm not sure why it's not picking up this setting from .cargo/config.toml like the other distros.

Hey @yonas thanks for the hint it works.
We are also making sure to copy the `config.toml` to the home dir on CI but still fails with the same error. I wonder if fails on the `nightly` build too.
Anyway, let's use `RUSTFLAGS` for now.

**Comment by joseluisq** [comment]
Please give it a test and let me know your thoughts on it.

**Comment by yonas** [comment]
After reading [this post](https://blog.logrocket.com/using-prometheus-metrics-in-a-rust-web-service), I recommend adding a few metrics: incoming requests, connected clients, response code, response duration.

**Comment by joseluisq** [comment]
> After reading [this post](https://blog.logrocket.com/using-prometheus-metrics-in-a-rust-web-service), I recommend adding a few metrics: incoming requests, connected clients, response code, response duration.

Sure, those server metrics sound useful. I think they can be added after this PR gets merged first as a way to improve the metrics feature in general.

However, I also think that server metrics should be the default rather than the Tokio runtime metrics though. But this can easily be enhanced in the next interactions.

**Comment by joseluisq** [comment]
Feel free to continue enhancing the metrics feature. 

Thanks @pl4nty!

**Comment by pl4nty** [comment]
Great to see this merged! Thanks for adding tests @joseluisq, I had a local branch but couldn't figure them out. Hopefully I'll have time to add more metrics in a month or two

**Comment by chrissnell** [comment]
Here's a first attempt at request metrics:

https://github.com/static-web-server/static-web-server/pull/631

**Pull request merged**
