### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
## Description

Found via `codespell -L crate`

### CODE REVIEW

**Comment by joseluisq** [comment]
Nice!

BTW are you interested in adding a [CI typos check](https://github.com/crate-ci/typos)? It would be great.
But I let that in your side as optional.

**Comment by kianmeng** [comment]
@joseluisq 

Regarding https://github.com/crate-ci/typos, didn't realize Rust ecosystem has its own spelling checker! Thanks for sharing. :partying_face:

Do you want to add the typos check CI job in separate PR or in this PR instead?
Also, what do you think about prettify the whole repo using https://github.com/prettier/prettier?

**Comment by joseluisq** [comment]
> Do you want to add the typos check CI job in separate PR or in this PR instead?

Sure, another PR for that is a good idea.

> Also, what do you think about prettify the whole repo using https://github.com/prettier/prettier?

What essential might be prettify used for? Formatting/Linting markdown file only or?

**Comment by dlvoy** [comment]
I wonder if prettier won't be redundant since in pipeline there is already step for code format enforcing:
`cargo fmt --all -- --check`

**Comment by joseluisq** [comment]
Yes, prettier sounds redundant to me as well.
However, we can go with a new CI workflow for checking typos in a new PR.

**Review by joseluisq — APPROVED** [review]

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
